### ISSUE TITLE
Possilbe Serial model

### ISSUE THREAD

**Issue by josephillips85** [pdewacht/adlipt#11]
Hi 
im trying to make this work with. a serial OPL2 i already patch Wolf3d to send to the serial port and a arduino.
but for one reason looks like the the baud rate or parity configuration is wrong because the data goes with the music but no the actual register value that is requiered.

do you belive on this way should work?
or maybe modifiing the adlipt to get the data from 388 and send it via serial port

thanks

**Comment by volkertb** [comment]
It would be cool to have this working on a serial port. Is it fast enough, though? Wouldn't there be a noticeable latency? Will it require some kind of buffering?

**Comment by josephillips85** [comment]
Hi

That what I’m trying to do the good part I don’t see any slowdown on the
game at least with wolfestein 3D with a 486 computer

The bad thing is I’m still don’t know what’s is wrong with the data that
send over the serial port looks like some issue with baud rate or serial
com configuration on arduino.

That why im asking here if after a patch the game should send only register
and value over serial port?

**Comment by pdewacht** [comment]
I'm closing this, because this really doesn't have anything to do with the OPL2LPT software.

It's certainly possible to build a serial OPL2 gadget. I expect it'd work well with most software. For Adlib MOD players and such it's going to be too slow though. Some scattered thoughts below.

---

To begin: you shouldn't be trying to patch games if you're not even sure if your serial code is working. I'd approach it like this.

- First, focus on the serial communication. Start with sending text messages from DOS to the Arduino. There's lots of old books and textfiles that will help you with this.
- Next step is to implement the OPL2 interface code. Adapt a simple OPL2 program on the PC for which you have the source code as a test program (e.g. OPL2TEST in this repo).
- If you got that working, you know the Arduino code works and you know you can send data from DOS. Now you can start thinking about patching "real" programs or porting the ADLIPT TSR.

---

The only values that _need_ to be transmitted are the address and value pairs. But instead of transmitting raw bytes, I'd define a little message format such as this:
- `01 xx`: select address $xx
- `02 xx`: write byte $xx to selected address
- `03 xx yy`: select address $xx, write byte $yy

Obviously the combined command is more efficient bandwidth-wise, but for some software the other two might be much more convenient.

An additional advantage is that this scheme can be extended to the OPL3:

- `04 xx`: select address $1xx
- `05 xx yy`: select address $1xx, write byte $yy

And even to multi-chip boards.

---

DOS software needs delay loops when accessing the OPL chip. It seems best to patch that oud, and implement it on the microcontroller instead. The reason is that DOS games could not time these short delays accurately, and thus they delay longer than strictly necessary. And serial transmission is already slow.

----

There's two kinds of serial chips common in DOS PC's: the newer 16550, which has a 16-byte TX buffer, and the older 8250, which doesn't. I think you'll really want a 16550.

**Comment by josephillips85** [comment]
Hey peter

Thanks for the clarification that help a lot.

What I’m using on Arduino is the Maarten Jensen’s serial pass through
sketch That is working well on dosbox with him patch.

Also I patch the vgm player to work with this sketch sending a address and
a value .

So the arduino part is working as expected.

My goal was using adpatch to only patch the games and send the data through
serial port but looks like something in missing on this part.

Thanks for your time and help

Best regards
Jose
