### ISSUE TITLE
Patch for Apogee game Dark Ages (the first AdLib game!)

### ISSUE THREAD

**Issue by reeshub** [pdewacht/adlipt#9]
Hi All! I notice that Dark Ages by Apogee isn't in the list of supported games for ADPATCH. I think this would be a great win for OPL2/3LPT because it was the first shareware game with AdLib support and so is historically important in the AdLib world. It was also recently released by them as Freeware.

I tried following the instructions to create my own patch and have successfully disassembled all of the game's data files using ndisasm, but there are no references to the address 0x388 or 0x389 as expected.

I'm a developer but don't have any experience with x86 machine code, but I'm willing to learn the basics if needs be to get this working. Could someone maybe point me in the right direction? Or even better create a patch so I can see how it works?

Thanks!

**Comment by pdewacht** [comment]
Hi! I took a look at Dark Ages. The game stores the AdLib address in a global variable, which means that it doesn't appear as a constant in the code. That makes finding the right function more difficult, you basically have to look at all code that uses IN/OUT opcodes and decide if it's AdLib code or not. (Actually a better way would probably be to use a debugger and put a breakpoint on the 0x388. But I've never tried setting up a DOS debugger.)

As it happens though, the AdLib output routine is already recognized and patched nby one the existing patterns :) And the AdLib detection routine seems to be more or less the same as the one used in Commander Keen, just compiled with a different compiler (or different compiler options), so that needed just a slight generalization of the Keen pattern.

If you're not familiar with x86 assembler, I guess a good way of learning is to take the source code of some old game ([here's a good collection](https://www.classicdosgames.com/misc/source.html)), figure out how the sound functions work, and then try to find the equivalent x86 code in the published EXE.

**Comment by pdewacht** [comment]
(BTW, in the commit I used a Ragel pattern to describe the x86 code. I don't think that's explained in the tutorial. Ragel is a language to write structured regex-like patterns to match binary data. It comes in very handy, because you often get slight variations in a company's patterns due to compiler changes etc, but it's not great for readability.)

**Comment by reeshub** [comment]
Peter, I just wanted to thank you for your quick response and comprehensive answer. I wasn't sure how actively maintained this project would be. Your efforts are very much appreciated!

I probably should have tried the patcher but as Dark Ages doesn't appear the official list of compatible games I didn't think it would be worth trying. I suggest you add it to the list just in case anyone else comes looking. :)

Thanks once again. I'll definitely take a look at the code and read up on Ragel.
